name: CI Pipeline (Dev)

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and test (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.203'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Run Analysis (Begin, Build, Test, End)
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PR_KEY: ${{ github.event.pull_request.number }}
          PR_BRANCH: ${{ github.head_ref }}
          PR_BASE: ${{ github.base_ref }}
          
        run: |
          [string[]]$PR_ARGS = @()
          
          if ([string]::IsNullOrWhiteSpace($env:PR_KEY) -ne $true) {
              Write-Host ">>> Running Pull Request analysis for PR #$env:PR_KEY"
              $PR_ARGS += "/d:sonar.pullrequest.key=$env:PR_KEY"
              $PR_ARGS += "/d:sonar.pullrequest.branch=$env:PR_BRANCH"
              $PR_ARGS += "/d:sonar.pullrequest.base=$env:PR_BASE"
          } 
          else {
              Write-Host ">>> Running Main Branch analysis."
              $PR_ARGS += "/d:sonar.branch.name=${{ github.ref_name }}"
          }

          dotnet sonarscanner begin `
            /k:"AndrodenBY_SubsTracker" `
            /o:"androdenby" `
            /d:sonar.login="$env:SONAR_TOKEN" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" `
            /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" `
            /d:sonar.exclusions="**/Migrations/**,**/Dockerfile,**/*appsettings*.json" `
            /d:sonar.scm.revision="${{ github.sha }}" `
            @PR_ARGS
                                
          dotnet sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"

      - name: Restore dependencies
        run: dotnet restore IMS/IMS.sln

      - name: Build
        run: dotnet build IMS/IMS.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test IMS/IMS.sln
          --configuration Release 
          --no-build 
          --logger "trx" 
          --results-directory TestResults
