name: CI Pipeline (Dev)

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]
  workflow_dispatch:

jobs:
  build:
    name: Build, Test, and Sonar Analysis (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.203'

      - name: Install Coverlet for .NET
        run: dotnet tool install --global coverlet.console

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Create TestResults folder if not exists
        run: mkdir -p TestResults

      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: pwsh
        run: |
          $projectKey = "zenavasilkov_IMS"
          $organization = "evgeny"
          $solutionPath = "IMS/IMS/IMS.sln"
          $coverageReportPath = "coverage.opencover.xml"
          $sonarCoverageParam = "/d:sonar.cs.opencover.reportsPaths=""$coverageReportPath"""

          dotnet-sonarscanner begin /k:"$projectKey" /o:"$organization" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" $sonarCoverageParam

          dotnet build $solutionPath --no-incremental

          dotnet test $solutionPath `
              --no-build `
              /p:CollectCoverage=true `
              /p:CoverletOutputFormat=opencover `
              /p:CoverletOutput="$coverageReportPath"

          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"