name: CI Pipeline (Dev)

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Coverlet for .NET
        run: dotnet tool install --global coverlet.console

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: SonarQube Begin Analysis
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          $projectKey = "zenavasilkov_IMS"
          $organization = "evgeny"
          $coverageReportPath = "coverage.opencover.xml"
          $sonarCoverageParam = "/d:sonar.cs.opencover.reportsPaths=""$coverageReportPath"""

          dotnet-sonarscanner begin `
              /k:"$projectKey" `
              /o:"$organization" `
              /d:sonar.login="$env:SONAR_TOKEN" `
              $sonarCoverageParam
              
      - name: Build Solution
        shell: pwsh
        run: |
          $solutionPath = "IMS/IMS.sln"
          dotnet build $solutionPath --no-incremental

      - name: Run Tests and Collect Coverage
        shell: pwsh
        run: |
          $solutionPath = "IMS/IMS.sln"
          $coverageReportPath = "coverage.opencover.xml"

          dotnet test $solutionPath `
              --no-build `
              /p:CollectCoverage=true `
              /p:CoverletOutputFormat=opencover `
              /p:CoverletOutput="$coverageReportPath"
              
      - name: SonarQube End Analysis
        shell: pwsh
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner end /d:sonar.login="$env:SONAR_TOKEN"
